name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-coding-style:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check coding style
      run: cargo fmt --check --all

  build:
    needs: [check-coding-style]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  tests:
    needs: [build]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose -- --nocapture
    
  mutation-tests:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-mutants
        run: cargo install --locked cargo-mutants
      - name: Run mutant tests
        run: cargo mutants -- --all-features
      - name: Archive results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: mutation-report
          path: mutants.out
    
  benchmark-tests:
    needs: [build]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --benches
